import { useEffect, useRef, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import { Galleries, uploadFile } from "../lib/api"

export default function GaleriFormPage(){
  const { id }=useParams(); const isEdit=!!id; const navigate=useNavigate(); const fileRef=useRef<HTMLInputElement>(null)
  const [form,setForm]=useState({title:"",description:"",coverUrl:"",eventDate:""}); const [loading,setLoading]=useState(isEdit); const [uploading,setUploading]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{if(!id)return; let off=false; setLoading(true); Galleries.get(Number(id)).then(g=>{if(off)return; setForm({title:g.title,description:g.description??"",coverUrl:g.cover_url??"",eventDate:g.event_date?g.event_date.slice(0,10):""})}).catch(e=>{if(!off)setError(e instanceof Error?e.message:"Gagal memuat")}).finally(()=>{if(!off)setLoading(false)}); return()=>{off=true}},[id])
  async function handleFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]; if(!file)return; setUploading(true); try{const r=await uploadFile(file); setForm(f=>({...f,coverUrl:r.url}))}catch(err){alert(err instanceof Error?err.message:"Upload gagal")}finally{setUploading(false); e.target.value=""}}
  async function handleSubmit(e:React.FormEvent){e.preventDefault(); setSubmitting(true); setError(null); const payload={title:form.title,description:form.description||null,coverUrl:form.coverUrl||null,eventDate:form.eventDate||null}; try{if(isEdit) await Galleries.update(Number(id),payload); else await Galleries.create(payload); navigate("/galeri")}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan")}finally{setSubmitting(false)}}
  return <AppLayout><div className="max-w-2xl"><Link to="/galeri" className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali ke Galeri</Link><h1 className="mt-3 text-2xl font-bold text-slate-900 dark:text-slate-100">{isEdit?"Edit Album":"Album Baru"}</h1>{error&&<div className="mt-4 rounded-xl bg-rose-50 ring-1 ring-rose-200 text-rose-700 text-sm p-3 dark:bg-rose-500/10 dark:ring-rose-500/30 dark:text-rose-300">{error}</div>}{loading?<div className="mt-5 text-slate-500 dark:text-slate-400">Memuat…</div>:<form onSubmit={handleSubmit} className="mt-5 rounded-2xl bg-white ring-1 ring-slate-200 p-5 grid gap-4 dark:bg-slate-900 dark:ring-slate-800"><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Judul *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input-base" /></label><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Tanggal Kegiatan</span><input type="date" value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})} className="input-base" /></label><div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Cover Album</span>{form.coverUrl&&<div className="mb-2 relative inline-block"><img src={form.coverUrl} alt="" className="h-24 rounded-lg ring-1 ring-slate-200 object-cover dark:ring-slate-700"/><button type="button" onClick={()=>setForm({...form,coverUrl:""})} className="absolute top-1 right-1 px-1.5 py-0.5 rounded-md text-xs bg-rose-600 text-white">×</button></div>}<div className="flex gap-2"><input value={form.coverUrl} onChange={e=>setForm({...form,coverUrl:e.target.value})} placeholder="URL gambar atau klik Upload" className="input-base flex-1"/><input ref={fileRef} type="file" accept="image/*" onChange={handleFile} hidden/><button type="button" onClick={()=>fileRef.current?.click()} disabled={uploading} className="btn-secondary disabled:opacity-50">{uploading?"Upload…":"Upload"}</button></div></div><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Deskripsi</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input-base" /></label><div className="flex justify-end gap-2"><Link to="/galeri" className="btn-secondary">Batal</Link><button disabled={submitting} className="btn-primary disabled:opacity-50">{submitting?"Menyimpan…":"Simpan"}</button></div></form>}</div></AppLayout>
}
