import { useEffect, useState } from "react"
import { Link, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import { AlertBox, TableSkeleton } from "../components/UiState"
import { Classes, type Klass, type Student } from "../lib/api"

type Detail=Klass & {students:Pick<Student,"id"|"nis"|"nisn"|"name"|"gender"|"status">[]}
export default function KelasDetailPage(){const{id}=useParams();const[item,setItem]=useState<Detail|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);useEffect(()=>{(async()=>{try{setLoading(true);setItem(await Classes.get(Number(id)))}catch(e){setError(e instanceof Error?e.message:"Gagal memuat kelas")}finally{setLoading(false)}})()},[id]);return <AppLayout><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/kelas" className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali</Link><h1 className="mt-1 text-2xl font-bold text-slate-900 dark:text-slate-100">{item?.name||"Detail Kelas"}</h1></div>{item&&<Link to={`/kelas/${item.id}/edit`} className="btn-primary">Edit</Link>}</div>{error&&<div className="mt-4"><AlertBox>{error}</AlertBox></div>}{loading?<div className="mt-5"><TableSkeleton rows={5} cols={3}/></div>:item&&<><div className="mt-5 grid gap-3 md:grid-cols-4"><Info label="Jenjang" value={item.education_level_name||item.grade_level}/><Info label="Tingkat" value={item.grade_level_name}/><Info label="Tahun Ajaran" value={item.academic_year_name}/><Info label="Wali Kelas" value={item.teacher_name}/></div><section className="mt-5 rounded-2xl bg-white ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800 overflow-hidden"><div className="p-4 font-bold">Daftar Siswa ({item.students.length})</div><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{item.students.map(s=><tr key={s.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-3 font-medium"><Link to={`/siswa/${s.id}`} className="text-primary-700 dark:text-primary-300">{s.name}</Link></td><td className="px-4 py-3 text-slate-500">{s.nis||"—"}</td><td className="px-4 py-3 text-slate-500">{s.gender||"—"}</td><td className="px-4 py-3 text-slate-500 capitalize">{s.status}</td></tr>)}</tbody></table></div></section></>}</AppLayout>}
function Info({label,value}:{label:string;value:any}){return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-bold text-slate-900 dark:text-slate-100">{value||"—"}</div></div>}
