import { useEffect, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import Select from "../components/Select"
import { Announcements, Classes, type Klass } from "../lib/api"

export default function PengumumanFormPage() {
  const { id } = useParams(); const isEdit = !!id; const navigate = useNavigate()
  const [classes, setClasses] = useState<Klass[]>([])
  const [form, setForm] = useState({ title: "", body: "", targetClassId: "" })
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { let off=false; (async()=>{ setLoading(true); try { const [c,a]=await Promise.all([Classes.list(), Announcements.list()]); if(off)return; setClasses(c.items); if(isEdit){ const item=a.items.find(x=>x.id===Number(id)); if(!item) throw new Error("Pengumuman tidak ditemukan"); setForm({title:item.title, body:item.body, targetClassId:item.target_class_id ? String(item.target_class_id) : ""}) } } catch(e){ if(!off)setError(e instanceof Error?e.message:"Gagal memuat") } finally{ if(!off)setLoading(false)} })(); return()=>{off=true} }, [id,isEdit])
  async function handleSubmit(e: React.FormEvent){ e.preventDefault(); setSubmitting(true); setError(null); const payload={title:form.title, body:form.body, targetClassId: form.targetClassId ? Number(form.targetClassId) : null}; try{ if(isEdit) await Announcements.update(Number(id), payload); else await Announcements.create(payload); navigate("/pengumuman") }catch(e){ setError(e instanceof Error?e.message:"Gagal menyimpan") }finally{ setSubmitting(false) } }
  return <AppLayout><div className="max-w-3xl"><Link to="/pengumuman" className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali ke Pengumuman</Link><h1 className="mt-3 text-2xl font-bold text-slate-900 dark:text-slate-100">{isEdit?"Edit Pengumuman":"Buat Pengumuman"}</h1>{error&&<div className="mt-4 rounded-xl bg-rose-50 ring-1 ring-rose-200 text-rose-700 text-sm p-3 dark:bg-rose-500/10 dark:ring-rose-500/30 dark:text-rose-300">{error}</div>}{loading?<div className="mt-5 text-slate-500 dark:text-slate-400">Memuat…</div>:<form onSubmit={handleSubmit} className="mt-5 rounded-2xl bg-white ring-1 ring-slate-200 p-5 grid gap-4 dark:bg-slate-900 dark:ring-slate-800"><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Judul *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input-base" /></label><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Isi *</span><textarea required rows={8} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} className="input-base" /></label><div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Sasaran Kelas</span><Select value={form.targetClassId} onChange={v=>setForm({...form,targetClassId:v})} options={[{value:"",label:"Semua kelas"},...classes.map(c=>({value:String(c.id),label:c.name}))]} /></div><div className="flex justify-end gap-2"><Link to="/pengumuman" className="btn-secondary">Batal</Link><button disabled={submitting} className="btn-primary disabled:opacity-50">{submitting?"Menyimpan…":"Simpan"}</button></div></form>}</div></AppLayout>
}
