import { useEffect, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import Select from "../components/Select"
import { Reports, Students, type Student } from "../lib/api"

function defaultSemester(): string { const d=new Date(); const y=d.getFullYear(); const m=d.getMonth()+1; return `${m>=7?`${y}/${y+1}`:`${y-1}/${y}`} ${m>=7?"Ganjil":"Genap"}` }

export default function RaporFormPage(){
  const { id }=useParams(); const isEdit=!!id; const navigate=useNavigate()
  const [students,setStudents]=useState<Student[]>([]); const [form,setForm]=useState({studentId:"", semester:defaultSemester(), body:""})
  const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{let off=false;(async()=>{setLoading(true);try{const [s,r]=await Promise.all([Students.list({status:"aktif"}),Reports.list()]); if(off)return; setStudents(s.items); if(isEdit){const item=r.items.find(x=>x.id===Number(id)); if(!item) throw new Error("Rapor tidak ditemukan"); setForm({studentId:String(item.student_id), semester:item.semester, body:item.body})}}catch(e){if(!off)setError(e instanceof Error?e.message:"Gagal memuat")}finally{if(!off)setLoading(false)}})();return()=>{off=true}},[id,isEdit])
  async function handleSubmit(e:React.FormEvent){e.preventDefault(); if(!form.studentId)return; setSubmitting(true); setError(null); try{ if(isEdit) await Reports.update(Number(id),{semester:form.semester,body:form.body}); else await Reports.create({studentId:Number(form.studentId),semester:form.semester,body:form.body}); navigate("/rapor") }catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan")}finally{setSubmitting(false)}}
  return <AppLayout><div className="max-w-3xl"><Link to="/rapor" className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali ke Rapor</Link><h1 className="mt-3 text-2xl font-bold text-slate-900 dark:text-slate-100">{isEdit?"Edit Rapor":"Buat Rapor"}</h1>{error&&<div className="mt-4 rounded-xl bg-rose-50 ring-1 ring-rose-200 text-rose-700 text-sm p-3 dark:bg-rose-500/10 dark:ring-rose-500/30 dark:text-rose-300">{error}</div>}{loading?<div className="mt-5 text-slate-500 dark:text-slate-400">Memuat…</div>:<form onSubmit={handleSubmit} className="mt-5 rounded-2xl bg-white ring-1 ring-slate-200 p-5 grid gap-4 dark:bg-slate-900 dark:ring-slate-800">{!isEdit&&<div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Siswa *</span><Select required value={form.studentId} onChange={v=>setForm({...form,studentId:v})} placeholder="— pilih siswa —" options={students.map(s=>({value:String(s.id),label:s.name,hint:s.class_name||undefined}))}/></div>}<label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Semester *</span><input required value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})} className="input-base" /></label><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Catatan Perkembangan *</span><textarea required rows={10} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} className="input-base" /></label><div className="flex justify-end gap-2"><Link to="/rapor" className="btn-secondary">Batal</Link><button disabled={submitting} className="btn-primary disabled:opacity-50">{submitting?"Menyimpan…":"Simpan"}</button></div></form>}</div></AppLayout>
}
