import { useEffect, useState } from "react"
import { Link, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import { AlertBox, TableSkeleton } from "../components/UiState"
import { Students, waLink, type Student } from "../lib/api"

export default function SiswaDetailPage(){
  const {id}=useParams(); const [item,setItem]=useState<Student|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{(async()=>{try{setLoading(true); setItem(await Students.get(Number(id)))}catch(e){setError(e instanceof Error?e.message:"Gagal memuat siswa")}finally{setLoading(false)}})()},[id])
  const wa=item?.parent_wa?waLink(item.parent_wa,`Halo ${item.parent_name||"Bapak/Ibu"}, informasi terkait ananda ${item.name}.`):null
  return <AppLayout><Header back="/siswa" title={item?.name||"Detail Siswa"} action={item&&<Link to={`/siswa/${item.id}/edit`} className="btn-primary">Edit</Link>}/>{error&&<div className="mt-4"><AlertBox>{error}</AlertBox></div>}{loading?<div className="mt-5 rounded-2xl bg-white p-4 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><TableSkeleton rows={5} cols={2}/></div>:item&&<div className="mt-5 grid gap-4 lg:grid-cols-3"><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"><div className="flex items-center gap-4">{item.photo_url?<img src={item.photo_url} className="h-20 w-20 rounded-2xl object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl bg-primary-50 text-2xl font-black text-primary-700 dark:bg-primary-500/10 dark:text-primary-200">{item.name[0]}</div>}<div><h1 className="text-xl font-bold text-slate-900 dark:text-slate-100">{item.name}</h1><p className="text-sm text-slate-500">{item.nis||"NIS —"}{item.nisn?` · NISN ${item.nisn}`:""}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold capitalize dark:bg-slate-800">{item.status}</span></div></div>{wa&&<a href={wa} target="_blank" rel="noreferrer" className="btn-secondary mt-4 w-full justify-center">Hubungi Wali via WA</a>}</section><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800 lg:col-span-2"><h2 className="font-bold">Biodata</h2><Grid rows={[["Kelas",item.class_name],["Nama panggilan",item.nickname],["Gender",item.gender],["TTL",[item.birth_place,item.birth_date].filter(Boolean).join(", ")],["Agama",item.religion],["Alamat",item.address],["Gol. darah",item.blood_type],["Alergi",item.allergies],["Catatan medis",item.medical_notes],["Kontak darurat",[item.emergency_contact_name,item.emergency_contact_phone].filter(Boolean).join(" · ")]]}/></section><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800 lg:col-span-3"><h2 className="font-bold">Wali / Orang Tua</h2><Grid rows={[["Nama",item.parent_name],["WhatsApp",item.parent_wa],...(item.guardians||[]).flatMap((g,i): [string, any][] => [[`Wali ${i+1}`,`${g.relation||""} ${g.name||""}`],[`Kontak ${i+1}`,[g.phone,g.whatsapp,g.email].filter(Boolean).join(" · ")]])]}/></section></div>}</AppLayout>
}
function Header({back,title,action}:{back:string;title:string;action?:React.ReactNode}){return <div className="flex flex-wrap items-center justify-between gap-3"><div><Link to={back} className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali</Link><h1 className="mt-1 text-2xl font-bold text-slate-900 dark:text-slate-100">{title}</h1></div>{action}</div>}
function Grid({rows}:{rows:[string,any][]}){return <div className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 text-sm font-medium text-slate-900 dark:text-slate-100">{v||"—"}</div></div>)}</div>}
