import { useEffect, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import AppLayout from "../components/AppLayout"
import Select from "../components/Select"
import MonthPicker from "../components/MonthPicker"
import { Classes, Spp, Students, type Klass, type Student, type SppInvoice } from "../lib/api"

function currentPeriod(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function due(p:string){const [y,m]=p.split("-").map(Number);return new Date(y,m-1,10).toISOString().slice(0,10)}
function rp(n:number|string){return "Rp "+Number(n).toLocaleString("id-ID")}

export default function SppFormPage(){
  const { id } = useParams(); const mode = location.pathname.includes("generate") ? "batch" : id ? "pay" : "new"
  const navigate=useNavigate(); const [classes,setClasses]=useState<Klass[]>([]); const [students,setStudents]=useState<Student[]>([]); const [invoice,setInvoice]=useState<SppInvoice|null>(null)
  const [form,setForm]=useState({studentId:"",classId:"",period:currentPeriod(),amount:150000,dueDate:due(currentPeriod()),paidAmount:0,method:"cash" as "cash"|"transfer"|"lain"})
  const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const [result,setResult]=useState<string|null>(null)
  useEffect(()=>{Promise.all([Classes.list(),Students.list({status:"aktif"}),Spp.list()]).then(([c,s,sp])=>{setClasses(c.items);setStudents(s.items); if(id){const inv=sp.items.find(x=>x.id===Number(id)); if(!inv) throw new Error("Tagihan tidak ditemukan"); setInvoice(inv); setForm(f=>({...f,paidAmount:Number(inv.paid_amount)||Number(inv.amount),method:(inv.method as typeof f.method)||"cash"}))} else setForm(f=>({...f,studentId:String(s.items[0]?.id||"")}))}).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat")).finally(()=>setLoading(false))},[id])
  async function submit(e:React.FormEvent){e.preventDefault();setSubmitting(true);setError(null);setResult(null);try{ if(mode==="batch"){const r=await Spp.batch({classId:form.classId?Number(form.classId):null,period:form.period,amount:form.amount,dueDate:form.dueDate});setResult(`Berhasil membuat ${r.created} tagihan baru dari ${r.total} siswa.`)} else if(mode==="pay"&&id){await Spp.pay(Number(id),{paidAmount:form.paidAmount,method:form.method});navigate("/spp")} else {await Spp.create({studentId:Number(form.studentId),period:form.period,amount:form.amount,dueDate:form.dueDate});navigate("/spp")}}catch(e){setError(e instanceof Error?e.message:"Gagal")}finally{setSubmitting(false)}}
  const title=mode==="batch"?"Generate Tagihan SPP":mode==="pay"?"Catat Pembayaran SPP":"Tambah Tagihan SPP"
  return <AppLayout><div className="max-w-2xl"><Link to="/spp" className="text-sm font-semibold text-primary-700 dark:text-primary-300">← Kembali ke SPP</Link><h1 className="mt-3 text-2xl font-bold text-slate-900 dark:text-slate-100">{title}</h1>{error&&<div className="mt-4 rounded-xl bg-rose-50 ring-1 ring-rose-200 text-rose-700 text-sm p-3 dark:bg-rose-500/10 dark:ring-rose-500/30 dark:text-rose-300">{error}</div>}{result&&<div className="mt-4 rounded-xl bg-emerald-50 ring-1 ring-emerald-200 text-emerald-700 text-sm p-3">{result}</div>}{loading?<div className="mt-5 text-slate-500">Memuat…</div>:<form onSubmit={submit} className="mt-5 rounded-2xl bg-white ring-1 ring-slate-200 p-5 grid gap-4 dark:bg-slate-900 dark:ring-slate-800">
    {mode==="pay"&&invoice&&<div className="rounded-xl bg-slate-50 dark:bg-slate-800/50 p-3 text-sm"><div>Siswa: <b>{invoice.student_name}</b></div><div>Periode: {invoice.period}</div><div>Tagihan: {rp(invoice.amount)}</div></div>}
    {mode==="new"&&<div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Siswa *</span><Select value={form.studentId} onChange={v=>setForm({...form,studentId:v})} required options={students.map(s=>({value:String(s.id),label:s.name,hint:s.class_name||undefined}))}/></div>}
    {mode==="batch"&&<><p className="text-sm text-slate-600 dark:text-slate-400">Buat tagihan untuk semua siswa aktif. Tagihan yang sudah ada akan dilewati.</p><div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Kelas</span><Select value={form.classId} onChange={v=>setForm({...form,classId:v})} options={[{value:"",label:"Semua kelas"},...classes.map(c=>({value:String(c.id),label:c.name}))]}/></div></>}
    {mode!=="pay"&&<><div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Periode</span><MonthPicker value={form.period} onChange={v=>setForm({...form,period:v,dueDate:due(v)})}/></div><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Nominal</span><input type="number" min={0} required value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})} className="input-base"/></label><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Jatuh Tempo</span><input type="date" required value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="input-base"/></label></>}
    {mode==="pay"&&<><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Jumlah Dibayar</span><input type="number" min={0} required value={form.paidAmount} onChange={e=>setForm({...form,paidAmount:Number(e.target.value)})} className="input-base"/></label><div><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Metode</span><Select value={form.method} onChange={v=>setForm({...form,method:v as typeof form.method})} options={[{value:"cash",label:"Tunai"},{value:"transfer",label:"Transfer"},{value:"lain",label:"Lainnya"}]}/></div></>}
    <div className="flex justify-end gap-2"><Link to="/spp" className="btn-secondary">Batal</Link><button disabled={submitting} className="btn-primary disabled:opacity-50">{submitting?"Memproses…":"Simpan"}</button></div>
  </form>}</div></AppLayout>
}
